startup;
ALTER SESSION SET "_ORACLE_SCRIPT"=true;
CREATE USER testuser IDENTIFIED BY "TestPwd@456";
GRANT CREATE SESSION TO testuser;
GRANT UNLIMITED TABLESPACE TO testuser;
GRANT DBA TO testuser;
QUIT;
